server:
  port: 8080
spring:
  application:
    name: hex-client

  data:
    mongodb:
      #uri: uri-cloud
      host: localhost
      port: 27018
      authentication-database: admin
      username: root
      password: root
      database: hexagonal


cluz:
  client:
    address:
      url: http://localhost:8095

kafka:
  topic:
    validated-cpf: topic-cpf-validated
    validation-cpf: topic-cpf-validation